# s3_id: AKIAIJSNERQB57W4ZRJA
# s3_secret: eSjzKGKH2De8YJSEvZkg9s8ccm4DorjyKCz9oiTO
# s3_bucket: jameswashington.me

# Below are examples of all the available configurations.
# See README for more detailed info on each of them.

site: _site/

index_document: index.html
error_document: 404.html

max_age:
  "assets/*": 6000
  "*": 300

gzip:
  - .html
  - .css
  - .md

gzip_zopfli: true

# See http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region for valid endpoints

exclude_from_upload:
  - README.md
  - s3_website.yml
  - deploy.sh

s3_reduced_redundancy: true

cloudfront_distribution_id: E2WBMOT44KM2C9

cloudfront_distribution_config:
  default_cache_behavior:
    min_TTL: <%= 60 * 60 * 24 %>
  aliases:
    quantity: 1
    items:
      CNAME: cdn.jameswashington.me

cloudfront_invalidate_root: true

cloudfront_wildcard_invalidation: true

# concurrency_level: 5

redirects:
  index.html: /

# routing_rules:
#   - condition:
#       key_prefix_equals: blog/some_path
#     redirect:
#       host_name: blog.example.com
#       replace_key_prefix_with: some_new_path/
#       http_redirect_code: 301
