name: James Washington
description: Personal blog and portfolio.
markdown: kramdown
highlighter: rouge
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - README.md
site: "//jameswashington.me"
disqus: jbw014
gems:
  - jekyll
  - jekyll-gist
  - kramdown
collections:
  work:
    output: true
